# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\description_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DescriptionDialog(object):
    def setupUi(self, DescriptionDialog):
        DescriptionDialog.setObjectName("DescriptionDialog")
        DescriptionDialog.resize(612, 488)
        self.verticalLayout = QtWidgets.QVBoxLayout(DescriptionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Description_lbl = QtWidgets.QLabel(DescriptionDialog)
        self.Description_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Description_lbl.setObjectName("Description_lbl")
        self.verticalLayout.addWidget(self.Description_lbl)
        self.Description_edit = QtWidgets.QTextEdit(DescriptionDialog)
        self.Description_edit.setMarkdown("")
        self.Description_edit.setObjectName("Description_edit")
        self.verticalLayout.addWidget(self.Description_edit)
        self.Decription_btn_box = QtWidgets.QDialogButtonBox(DescriptionDialog)
        self.Decription_btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Decription_btn_box.setCenterButtons(True)
        self.Decription_btn_box.setObjectName("Decription_btn_box")
        self.verticalLayout.addWidget(self.Decription_btn_box)
