# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\group_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupDialog(object):
    def setupUi(self, GroupDialog):
        GroupDialog.setObjectName("GroupDialog")
        GroupDialog.resize(537, 405)
        self.Group_dialog_layout = QtWidgets.QVBoxLayout(GroupDialog)
        self.Group_dialog_layout.setObjectName("Group_dialog_layout")
        self.Group_dialog_lbl = QtWidgets.QLabel(GroupDialog)
        self.Group_dialog_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.Group_dialog_lbl.setObjectName("Group_dialog_lbl")
        self.Group_dialog_layout.addWidget(self.Group_dialog_lbl)
        self.Group_dialog_line = QtWidgets.QFrame(GroupDialog)
        self.Group_dialog_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.Group_dialog_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Group_dialog_line.setObjectName("Group_dialog_line")
        self.Group_dialog_layout.addWidget(self.Group_dialog_line)
        self.Group_dialog_add_group_btn = QtWidgets.QPushButton(GroupDialog)
        self.Group_dialog_add_group_btn.setObjectName("Group_dialog_add_group_btn")
        self.Group_dialog_layout.addWidget(self.Group_dialog_add_group_btn)
        self.Group_dialog_btn_box = QtWidgets.QDialogButtonBox(GroupDialog)
        self.Group_dialog_btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.Group_dialog_btn_box.setObjectName("Group_dialog_btn_box")
        self.Group_dialog_layout.addWidget(self.Group_dialog_btn_box)
