# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\new_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewModelDialog(object):
    def setupUi(self, NewModelDialog):
        NewModelDialog.setObjectName("NewModelDialog")
        NewModelDialog.setEnabled(True)
        NewModelDialog.resize(362, 127)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NewModelDialog.sizePolicy().hasHeightForWidth())
        NewModelDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewModelDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.New_name_layout = QtWidgets.QHBoxLayout()
        self.New_name_layout.setObjectName("New_name_layout")
        self.New_name_lbl = QtWidgets.QLabel(NewModelDialog)
        self.New_name_lbl.setObjectName("New_name_lbl")
        self.New_name_layout.addWidget(self.New_name_lbl)
        self.New_name_edit = QtWidgets.QLineEdit(NewModelDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.New_name_edit.sizePolicy().hasHeightForWidth())
        self.New_name_edit.setSizePolicy(sizePolicy)
        self.New_name_edit.setObjectName("New_name_edit")
        self.New_name_layout.addWidget(self.New_name_edit)
        self.verticalLayout.addLayout(self.New_name_layout)
        self.New_location_layout = QtWidgets.QHBoxLayout()
        self.New_location_layout.setObjectName("New_location_layout")
        self.New_location_lbl = QtWidgets.QLabel(NewModelDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.New_location_lbl.sizePolicy().hasHeightForWidth())
        self.New_location_lbl.setSizePolicy(sizePolicy)
        self.New_location_lbl.setObjectName("New_location_lbl")
        self.New_location_layout.addWidget(self.New_location_lbl)
        self.New_location_edit = QtWidgets.QLineEdit(NewModelDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.New_location_edit.sizePolicy().hasHeightForWidth())
        self.New_location_edit.setSizePolicy(sizePolicy)
        self.New_location_edit.setObjectName("New_location_edit")
        self.New_location_layout.addWidget(self.New_location_edit)
        self.New_location_btn = QtWidgets.QPushButton(NewModelDialog)
        self.New_location_btn.setObjectName("New_location_btn")
        self.New_location_layout.addWidget(self.New_location_btn)
        self.verticalLayout.addLayout(self.New_location_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.New_btn_box = QtWidgets.QDialogButtonBox(NewModelDialog)
        self.New_btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.New_btn_box.setObjectName("New_btn_box")
        self.verticalLayout.addWidget(self.New_btn_box)
